CREATE TABLE Users(
    UserID VARCHAR2(100) PRIMARY KEY,
    FName VARCHAR2(50),
    LName VARCHAR2(50),
    Email VARCHAR2(100) UNIQUE,
    PhoneNo NUMBER(10),
    Role VARCHAR2(20),
    Institution VARCHAR2(100),
    DateCreated DATE DEFAULT SYSDATE
    );

CREATE TABLE Events(
    EventId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CreatorUserID VARCHAR2(100),
    Title VARCHAR2(200),
    Fee NUMBER(10,2),
    CreatedAt DATE DEFAULT SYSDATE,
    Description VARCHAR2(4000),
    NoOfSeats Number(5) CHECK (NoOfSeats >= 1),
    StartDate DATE,
    EndDate DATE,
    EventStatus VARCHAR2(20),
    EventType VARCHAR2(50),
    EventCategory VARCHAR2(50),
    Venue VARCHAR2(100),
    Image VARCHAR2(500),
    CONSTRAINT fk_creator FOREIGN KEY (CreatorUserID) REFERENCES Users(UserID) ON DELETE CASCADE
    );

CREATE TABLE Bookings(
    BookingID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserID VARCHAR2(100),
    EventId Number,
    BookingStatus VARCHAR2(20),
    NoOfParticipants NUMBER,
    BookingTimestamp DATE DEFAULT SYSDATE,
    ReservationDate DATE,
    CONSTRAINT fk_user FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE,
    CONSTRAINT fk_event FOREIGN KEY (EventId) REFERENCES Events(EventId) ON DELETE CASCADE
);

CREATE TABLE Payments(
    PaymentID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BookingID NUMBER,
    TransactionRef VARCHAR2(100),
    PaymentTimestamp DATE DEFAULT SYSDATE,
    PaymentStatus VARCHAR2(20),
    Amount Number(10,2) CHECK (Amount >= 0),
    PaymentMethod VARCHAR2(50),
    CONSTRAINT fk_booking FOREIGN KEY (BookingID) REFERENCES Bookings(BookingID) ON DELETE CASCADE
);

CREATE TABLE AdminActivityLogs(
    LogID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserID VARCHAR2(100),
    Action VARCHAR2(200),
    LogTimestamp DATE DEFAULT SYSDATE,
    CONSTRAINT fk_log_user FOREIGN KEY (UserID) REFERENCES Users(UserID)
);